### PR TITLE
Feature/evaluate

### PR DESCRIPTION
**Pull request by maximilianmetti**
Handle greater variety of PDE coefficient inputs. Mainly, dolfin functions and expressions can be used for coefficients, meaning that the coefficients can come from solutions of previously solved PDEs or previous iterates of a computed solution.

### CODE REVIEW

**Comment by arthbous** [comment]
What is the role of strict? Why not if expression is None then we return 0 vector?

**Comment by maximilianmetti** [comment]
Strict avoids using the default function (zeros), since this would cause the `eafe_assembly` to divide by zero.  That's why it's set to `True` for the diffusivity and is `False` (by default) for the convection and reaction terms.

**Comment by arthbous** [comment]
We could add float, int, array or np.ndarry which are the classic ones. 
I tried to add:
```Python
    if isinstance(expression, float) or isinstance(expression, float) \
        or isinstance(expression, np.ndarray) or isinstance(expression, list):
        return expression
```
At the begning but it gives an error.

**Comment by arthbous** [comment]
I get some weird error and warnings:

```
Testing variously defined coefficients...
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
--- Instant: compiling ---
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
--- Instant: compiling ---
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
--- Instant: compiling ---
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
--- Instant: compiling ---
*** Warning: Degree of exact solution may be inadequate for accurate result in errornorm.
*** Warning: Degree of exact solution may be inadequate for accurate result in errornorm.
Errors for various PDE coefficient representations are acceptable
Success!
Done. 
```

We could remove the dolfin warnings. Also I don't see in evaluation_test.py, a test if diffusivity is a float and not an Expression.

**Comment by maximilianmetti** [comment]
We can suppress those errors. The exact solution is constant so there won’t be any accuracy issues with quadrature. 

Also, `diffusivity` is a float (see line 15 in eval_test.py).

**Comment by arthbous** [comment]
Yeah, but you don't use it with assemble_eafe.

```
pyeafe.eafe_assemble(mesh, 1E-2, np.zeros(2))
```

**Comment by maximilianmetti** [comment]
@arthbous 
I'm a little confused.  These two lines show using a float to construct the eafe matrix:
https://github.com/thepnpsolver/pyeafe/blob/feature/evaluate/pyeafe/tests/evaluation_test.py#L15
https://github.com/thepnpsolver/pyeafe/blob/feature/evaluate/pyeafe/tests/evaluation_test.py#L103

**Comment by arthbous** [comment]
My bad. It works.

in pyeafe/tests/__init__.py : we need to add "evaluate_test"

in pyeafe/tests/evaluate_test.py we should add something like
```Python
import logging
logging.getLogger('FFC').setLevel(logging.WARNING)
```

In evaluate I don't see where it takes into account floats?
Also, what is the difference between defining a class and function inside a function?

**Comment by maximilianmetti** [comment]
@arthbous we don't add any tests individually to the `pyeafe/__init__.py`; so i don't think it's necessary for the `evaluate_test`.

In `evaluate.py`, see [this line](https://github.com/thepnpsolver/pyeafe/blob/feature/evaluate/pyeafe/evaluate.py#L72) that checks if the function passed into `create_safe_eval` is callable.  If it is not callable, it is considered a float, list, or numpy array.  A function returning the constant value passed defined is [here](https://github.com/thepnpsolver/pyeafe/blob/feature/evaluate/pyeafe/evaluate.py#L82).

Regarding classes vs defining functions within a function, we don't create instances of `create_safe_eval` that require inheritance or common class of methods. It dynamically creates a function each time it is called; this is like a constructor except that it only returns a function and not an object with methods and attributes.  That's why I went ahead and made this a function that returns a function based exclusively on the arguments.  Maybe in the future, this may need common methods or attributes across all `safe_function`s, but I do not think that is needed here and will only add an extra layer of complexity.

**Comment by maximilianmetti** [comment]
👍

**Pull request merged**
